### ISSUE TITLE
Support for audio >30s

### ISSUE THREAD

**Issue by cantabile-kwok** [xingchensong/S3Tokenizer#14]
Current code will raise RuntimeError for long audio clips (>30s for 50hz version).

```python
import s3tokenizer
import torch

tokenizer = s3tokenizer.load_model("speech_tokenizer_v1").cuda()  # or "speech_tokenizer_v1_25hz"

mels = []
for _ in range(4):
    audio = torch.randn(int(30.1*16000))
    mels.append(s3tokenizer.log_mel_spectrogram(audio))
mels, mels_lens = s3tokenizer.padding(mels)
codes, codes_lens = tokenizer.quantize(mels.cuda(), mels_lens.cuda())
```

Output:
```
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    codes, codes_lens = tokenizer.quantize(mels.cuda(), mels_lens.cuda())
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/s3tokenizer/model.py", line 298, in quantize
    hidden, code_len = self.encoder(mel, mel_len)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/s3tokenizer/model.py", line 167, in forward
    x = (x + self.positional_embedding[:x.shape[1], :]).to(x.dtype)
RuntimeError: The size of tensor a (1505) must match the size of tensor b (1500) at non-singleton dimension 1
```

I understand this is an expected behavior since the position encoding has a max of 1500, but it will be better to have a workaround with this (perhaps truncate and concatenate).

**Comment by Mddct** [comment]
可以按照文中提出的思路去提取： （大概是： 为了处理长篇语音，音频被分成 30 秒的片段，这些片段有 4 秒的重叠。每个 30 秒的窗口被独立标记）

https://arxiv.org/pdf/2412.18603

**Comment by Mddct** [comment]
参考这个： https://github.com/Mddct/s3tokenizer-long/tree/main
